FROM node:carbon

USER root

# install some basic library
RUN apt-get update && apt-get install -y --no-install-recommends \
	ca-certificates \
	curl \
	wget \
	openssh-server &&\
 	rm -rf /var/lib/apt/lists/* &&\
	sed -i 's|session    required     pam_loginuid.so|session    optional     pam_loginuid.so|g' /etc/pam.d/sshd &&\
mkdir -p /var/run/sshd

# Install updates & requirements:
#  * git, openssh-client, ca-certificates - clone & build
#  * curl, p7zip - to download & unpack Qt bundle
#  * build-essential, pkg-config, libgl1-mesa-dev - basic Qt build requirements
#  * libsm6, libice6, libxext6, libxrender1, libfontconfig1 - dependencies of Qt bundle run-file
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q update &&\
	apt-get -qq dist-upgrade && apt-get install -qq -y --no-install-recommends \
    git \
    openssh-client \
    p7zip \
    build-essential \
    pkg-config \
    libgl1-mesa-dev \
    libsm6 \
    libice6 \
    libxext6 \
    libxrender1 \
    libfontconfig1 \
	tmux \
	sudo \
	cscope \
    && apt-get -qq clean


# Set user jenkins to the image
RUN useradd -m -d /home/jenkins -s /bin/bash jenkins &&\
    echo "jenkins:jenkins" | chpasswd

USER jenkins

# set up coding environment
RUN mkdir /home/jenkins/git
WORKDIR /home/jenkins/git
RUN git clone https://github.com/xaiser/code_environment
RUN cp /home/jenkins/git/code_environment/.tmux.conf /home/jenkins
RUN cp /home/jenkins/git/code_environment/bashrc_v2 /home/jenkins/.bashrc
RUN cp /home/jenkins/git/code_environment/gitconfig_setting /home/jenkins/.gitconfig

# build vim
USER root
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q update &&\
	apt-get -qq dist-upgrade && apt-get install -qq -y --no-install-recommends \
    exuberant-ctags \
    python-dev \
	libperl-dev \
	libncurses5-dev \
	ruby-dev \
    && apt-get -qq clean

USER jenkins
RUN git clone https://github.com/vim/vim.git
WORKDIR /home/jenkins/git/vim
RUN ./configure --with-features=huge --enable-multibyte --enable-pythoninterp --enable-perlinterp --enable-rubyinterp --enable-cscope
RUN make

USER root
WORKDIR /home/jenkins/git/vim
RUN cd src && make install
USER jenkins
WORKDIR /

USER root
RUN adduser jenkins sudo
RUN echo "jenkins ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers

# Standard SSH port
EXPOSE 22

# Default command
CMD ["/usr/sbin/sshd", "-D"]
